name: Run Python Script Every 15 Minutes and on Demand

on:
  #schedule:
   # - cron: '*/15 * * * *'
  workflow_dispatch:
  
permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4
      - name: Run script
        run: python preferred.py
      - name: Commit and push if there are changes
        run: |
          git config --local user.email "20221805134@llu.edu.cn"
          git config --local user.name "smsjksk"
          git add -A
          git commit -m "Update IP list" -a || echo "No changes to commit"
          git push
