name: Optimized Masscan Scan and Convert

on:
  workflow_dispatch:

jobs:
  setup_and_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup environment
        run: |
          sudo apt-get update
          sudo apt-get install -y masscan
          sudo apt-get install -y python3-pip
          pip install -r https://raw.githubusercontent.com/EzXxY/CF-IP/main/requirements.txt
      
      - name: Download proxy-ip-part
        run: |
          wget -O proxy-ip-part.txt https://raw.githubusercontent.com/smashsjksk/CloudFlare-preferredIP/main/proxy-ip-part.txt

      - name: Run Masscan
        run: |
          sudo masscan -iL proxy-ip-part.txt -p 20000-60000 --exclude 255.255.255.255 -oX scan.xml --rate 250000000 --quiet
      
      - name: Upload scan result
        uses: actions/upload-artifact@v3
        with:
          name: scan
          path: scan.xml

  process_results:
    runs-on: ubuntu-latest
    needs: setup_and_scan
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download and process results
        run: |
          wget https://raw.githubusercontent.com/EzXxY/CF-IP/main/xml_to_csv_parser_updated_no_duplicates.py
          wget https://github.com/EzXxY/CF-IP/raw/main/txt_2_csv.py
          wget https://raw.githubusercontent.com/EzXxY/CF-IP/main/request.py
          python xml_to_csv_parser_updated_no_duplicates.py ./ ./05-可视化扫描结果.csv
          python request.py
          python txt_2_csv.py ./06-提取反代了CF的ip及端口.txt ./07-提取反代了CF的ip及端口.csv
      
      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: Results
          path: |
            05-可视化扫描结果.csv
            06-提取反代了CF的ip及端口.txt
            07-提取反代了CF的ip及端口.csv
